config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :todos, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :labels, only: [:index, :show, :edit, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :todo_labels, dependent: :destroy
  has_many :todo, through: :todo_labels
  enum status: { yet: 1, wip: 2, done: 3 }
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/todo_label.rb
class TodoLabel < ApplicationRecord
  belongs_to :label
  belongs_to :todo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
end

app/controllers/labels_controller.rb
class LabelsController
  def index
    @labels = Label.order(id: :asc).all
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :destroy]

  def index
    @todos = Todo.order(id: :desc).all
  end

  def create
    @todo = Todo.create! todo_params.merge(status: :yet)
    @todo.broadcast_append_later_to('todo_stream_channel')
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.turbo_stream
    end
  end

  def new
    @todo = Todo.new
  end

  def update
    @todo.update! todo_params
    @todo.broadcast_update_to('todo_stream_channel')
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.turbo_stream
    end
  end

  def edit; end

  def destroy
    @todo.broadcast_remove_to('todo_stream_channel')
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.turbo_stream
    end
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSpaSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo, class:"item" do %>
  <div class="ui grid">
    <div class="column ten wide"><%= todo.name %></div>
    <div class="column three wide">
      <%= button_to 'Delete', todo_path(todo), method: :delete, form: { data: { turbo_confirm: 'are you sure?' }}, class: "ui button" %>
    </div>
    <div class="column three wide">
      <%= link_to 'Edit', edit_todo_path(todo), data: { turbo_frame: todo }, class: "ui button" %>
    </div>
  </div>
<%end%>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.update :new_todo %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag @todo do %>
  <%= form_with(model: @todo, class: "ui form") do |form| %>
    <div class="ui grid">
      <div class="column ten wide"><%= form.text_field :name %></div>
      <div class="column six wide">
        <%= button_to 'update', todo_path(@todo), method: :patch, class: "ui button" %>
      </div>
    </div>
  <% end %>
<%end%>

app/views/todos/index.html.erb
<div class="ui grid centered">
  <div class="ui eight wide column">
    <h1>Todos</h1>
    <div id='todos' class="ui relaxed divided list">
      <% @todos.each do |todo| %>
        <%= render todo %>
      <% end %>
    </div>
    <%= turbo_frame_tag :new_todo, class:"item" %>
    <%= link_to '+ New Todo', new_todo_path, data: { turbo_frame: :new_todo }, class: "ui button",style: "margin-top: 1rem" %>
  </div>
</div>
<%= turbo_stream_from 'todo_stream_channel' %>

app/views/todos/new.html.erb
<%= turbo_frame_tag @todo do %>
  <%= form_with(model: @todo, class: "ui form") do |form| %>
    <div class="ui grid">
      <div class="column ten wide"><%= form.text_field :name %></div>
      <div class="column six wide">
        <%= button_to 'Create', todos_path, method: :post, class: "ui button" %>
      </div>
    </div>
  <% end %>
<%end%>